apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: lucasomx1685/guess-game-backend:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

          env:
            - name: FLASK_APP
              value: run.py
            - name: FLASK_DB_TYPE
              value: postgres
            - name: FLASK_DB_USER
              value: postgres
            - name: FLASK_DB_NAME
              value: postgres
            - name: FLASK_DB_PASSWORD
              value: secretpass
            - name: FLASK_DB_HOST
              value: db
            - name: FLASK_DB_PORT
              value: "5432"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP