FROM python:3.12

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_APP=run.py
ENV FLASK_DB_TYPE=postgres
ENV FLASK_DB_USER=postgres
ENV FLASK_DB_NAME=postgres
ENV FLASK_DB_PASSWORD=secretpass
ENV FLASK_DB_HOST=db
ENV FLASK_DB_PORT=5432

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
